# Generated by Django 2.0.2 on 2019-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0002_auto_20190117_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='module',
            field=models.CharField(choices=[('Owner', 'Owner'), ('User', 'User'), ('tpa', 'tpa'), ('admin', 'admin'), ('espdsp', 'espdsp')], max_length=20),
        ),
    ]
