# Generated by Django 2.0.2 on 2019-01-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0003_auto_20190117_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOTATransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('pub_key', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=20)),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.register')),
            ],
        ),
    ]
