# Generated by Django 2.0.2 on 2019-01-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0004_dotatransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownerFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('owner_file', models.FileField(upload_to='')),
            ],
        ),
    ]
