# Generated by Django 2.0.2 on 2019-01-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0005_ownerfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerfileupload',
            name='owner_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
