# Generated by Django 2.0.2 on 2019-01-22 14:48
import datetime
from django.db import migrations, models
from django.utils.timezone import utc

class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0007_auto_20190122_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerfileupload',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 22, 21, 45, 50, 115212, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownerfileupload',
            name='owner_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
