# Generated by Django 2.0.2 on 2019-01-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0008_auto_20190122_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerfileupload',
            name='uploadDate',
        ),
    ]
