# Generated by Django 2.0.2 on 2019-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0009_remove_ownerfileupload_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerfileupload',
            name='owner_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
