# Generated by Django 2.0.2 on 2019-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0010_auto_20190122_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOESPTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('file_path', models.URLField()),
                ('pub_key', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=30)),
                ('enc_file', models.FileField(upload_to='')),
            ],
        ),
    ]
