# Generated by Django 2.0.2 on 2019-02-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0013_ownerfileupload_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doesptransaction',
            name='enc_file',
            field=models.URLField(),
        ),
    ]
