# Generated by Django 2.0.2 on 2019-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0014_auto_20190204_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloudTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('enc_file', models.URLField()),
                ('pub_key', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=30)),
                ('attributes', models.CharField(max_length=500)),
                ('policies', models.CharField(max_length=500)),
            ],
        ),
    ]
