# Generated by Django 2.0.2 on 2019-03-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0017_dutatransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DODUTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('attributes', models.CharField(max_length=500)),
                ('user_list', models.CharField(max_length=500)),
            ],
        ),
    ]
