# Generated by Django 2.0.2 on 2019-03-14 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0018_dodutransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodutransaction',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
