# Generated by Django 2.0.2 on 2019-03-15 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0020_ductransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ductransaction',
            name='owner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
