# Generated by Django 2.0.2 on 2019-03-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0022_auto_20190316_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ductransaction',
            name='enc_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ductransaction',
            name='file_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
