# Generated by Django 2.0.2 on 2019-03-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0023_auto_20190316_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='DUCDECTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('pub_key', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('enc_file', models.URLField(blank=True, null=True)),
                ('dec_file', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
