# Generated by Django 2.0.2 on 2019-03-18 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0024_ducdectransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ductransaction',
            name='enc_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
