# Generated by Django 2.0.2 on 2019-03-18 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0025_auto_20190318_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducdectransaction',
            name='dec_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ducdectransaction',
            name='enc_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
