# Generated by Django 2.0.2 on 2019-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0027_auto_20190318_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerfileupload',
            name='owner_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
