# Generated by Django 2.1.7 on 2019-03-20 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0029_auto_20190319_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='doesptransaction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appAdmin.ownerFileUpload'),
            preserve_default=False,
        ),
    ]
