# Generated by Django 2.1.7 on 2019-03-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0030_doesptransaction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doesptransaction',
            name='enc_file',
        ),
        migrations.RemoveField(
            model_name='doesptransaction',
            name='file_path',
        ),
    ]
