# Generated by Django 2.1.7 on 2019-03-20 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0031_auto_20190320_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doesptransaction',
            name='owner',
        ),
        migrations.AddField(
            model_name='doesptransaction',
            name='enc_file',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doesptransaction',
            name='file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
