# Generated by Django 2.1.7 on 2019-03-20 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0033_auto_20190320_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotatransaction',
            name='_pub_key',
        ),
        migrations.AddField(
            model_name='dotatransaction',
            name='pub_key',
            field=models.BinaryField(default=b'1'),
            preserve_default=False,
        ),
    ]
