# Generated by Django 2.0.2 on 2019-04-21 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0037_auto_20190320_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='ductransaction',
            name='downloadCount',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
