# Generated by Django 2.0.2 on 2019-04-21 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0038_ductransaction_downloadcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ductransaction',
            name='downloadCount',
        ),
        migrations.AddField(
            model_name='cloudtransaction',
            name='downloadCount',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
