# Generated by Django 2.0.2 on 2019-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0039_auto_20190422_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtransaction',
            name='enc_file',
            field=models.CharField(max_length=100),
        ),
    ]
