# Generated by Django 2.0.2 on 2019-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0040_auto_20190422_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtransaction',
            name='downloadCount',
            field=models.PositiveIntegerField(),
        ),
    ]
