# Generated by Django 2.0.2 on 2019-04-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0041_auto_20190422_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='doesptransaction',
            name='reEnc_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doesptransaction',
            name='enc_file',
            field=models.CharField(max_length=100),
        ),
    ]
